import argparse
from pathlib import Path
import json
import os
import gzip
import traceback
import concurrent.futures as cf
from typing import List, Dict, Tuple, Set

import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.model_selection import StratifiedKFold
import time  # Added: for time statistics


# ========== Basic utilities ==========
def find_seq_txt_files(root_dir):
    """
    Recursively find .txt sequence files under root_dir (produced by gexf_to_java_seq.py).
    """
    return list(Path(root_dir).rglob('*.txt'))


def infer_label(path: Path, malware_key='malware', benign_key='benign'):
    parts = [p.lower() for p in path.parts]
    if malware_key.lower() in parts:
        return 'malware'
    elif benign_key.lower() in parts:
        return 'benign'
    else:
        return None


def path_sha_no_ext(p: Path) -> str:
    return p.stem


# ========== Sensitive API mapping and sequence parsing ==========
def load_sapi_mapping(sapi_path: Path) -> Tuple[Dict[int, str], Set[str]]:
    """
    Read the sensitive API list (one Java method signature per line) and build:
    - id_to_api: 1-based index -> API name (matches gexf_to_java_seq.py numbering)
    - sapi_set: set of sensitive API names
    """
    ordered, seen = [], set()
    with open(sapi_path, 'r', encoding='utf-8') as f:
        for line in f:
            api = line.strip()
            if api and api not in seen:
                seen.add(api)
                ordered.append(api)
    id_to_api = {i + 1: api for i, api in enumerate(ordered)}
    return id_to_api, set(ordered)


def extract_sensitive_apis_from_txt(txt_path: Path,
                                    id_to_api: Dict[int, str],
                                    sapi_set: Set[str]) -> List[str]:
    """
    Extract unique sensitive APIs used in a file (file-level) from .txt sequence files generated by gexf_to_java_seq.py.
    - Each line in the file is a sequence, default is space-separated 1-based integer IDs.
    - If a token in the sequence is not a digit (e.g., direct API name), include it only if it belongs to the sensitive set.
    Returns a sorted list of sensitive API names.
    """
    used = set()
    try:
        with open(txt_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                for tok in line.split():
                    if tok.isdigit():
                        idx = int(tok)
                        api = id_to_api.get(idx)
                        if api:
                            used.add(api)
                    else:
                        # Compatibility: if the output is a name, only accept it if it is found in the sensitive set
                        if tok in sapi_set:
                            used.add(tok)
    except FileNotFoundError:
        # Return empty if not found
        return []
    except Exception:
        # Let higher level handle other errors
        raise

    return sorted(used)


# ========== Cache ==========
def write_api_cache(cache_file: Path, apis: List[str]) -> None:
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(cache_file, "wt", encoding="utf-8") as f:
        for a in apis:
            f.write(a)
            f.write("\n")


def read_api_cache(cache_file: Path) -> List[str]:
    if not cache_file.exists():
        return []
    with gzip.open(cache_file, "rt", encoding="utf-8") as f:
        return [line.rstrip("\n") for line in f]


def preprocess_one_file(args_tuple) -> Dict:
    """
    Parallel task: Read one .txt sequence file -> use SAPI mapping to restore ID to sensitive API names -> deduplicate -> write to cache
    Returns dict with path, sha, label, cache_path, n_apis, error
    """
    (fpath_str, malware_key, benign_key, cache_dir_str, reuse_cache, id_to_api, sapi_set) = args_tuple

    fpath = Path(fpath_str)
    cache_dir = Path(cache_dir_str)
    sha = path_sha_no_ext(fpath)
    label = infer_label(fpath, malware_key, benign_key)
    out_cache = cache_dir / f"{sha}.txt.gz"

    ret = {
        "path": str(fpath),
        "sha": sha,
        "label": label,
        "cache_path": str(out_cache),
        "n_apis": 0,
        "error": ""
    }

    if label not in ("malware", "benign"):
        return ret

    try:
        if reuse_cache and out_cache.exists():
            # Read cache if already exists to get count
            apis = read_api_cache(out_cache)
            ret["n_apis"] = len(set(apis))
            return ret

        unique_apis = extract_sensitive_apis_from_txt(fpath, id_to_api, sapi_set)
        write_api_cache(out_cache, unique_apis)
        ret["n_apis"] = len(unique_apis)
    except Exception as e:
        ret["error"] = f"{e}\n{traceback.format_exc()}"
    return ret


# ========== Compute weights (from cache) ==========
def compute_weights_from_cache(train_items: List[Tuple[Path, str]],
                               cache_dir: Path,
                               min_count: int,
                               alpha: int = 2,
                               verbose: bool = False):
    """
    Compute "file-level presence count" of APIs in malware/benign categories from cache files, and compute entropy and weights.
    Steps:
      1. For each file, treat the API set as unique (boolean model).
      2. Accumulate for each API how many times it appears in malware (c_m(s)) and benign samples (c_b(s)).
      3. Filter APIs with total_count = c_m + c_b < min_count.
      4. Laplace smoothing: with c_m'(s) = c_m(s) + α, c_b'(s) = c_b(s) + α (alpha default 1) to avoid extreme 0/1 ratios.
         Note: Denominator uses the original sample count N_m, N_b, not (N + 2α) as in standard Bernoulli smoothing.
         For canonical form, change to:
             pm = (c_m + alpha) / (n_malware + 2 * alpha)
             pb = (c_b + alpha) / (n_benign + 2 * alpha)
      5. Compute within-class frequencies:
             pm_raw = c_m / N_m
             pb_raw = c_b / N_b
             pm = (c_m + α) / (N_m + 2*α)
             pb = (c_b + α) / (N_b + 2*α)
         (Set to 0 if the sample size is 0)
      6. Compute malicious preference ratio:
             p = pm / (pm + pb) (set to 0 if denominator is 0)
      7. Information entropy (natural log):
             H = -p ln p - (1-p) ln(1-p) (p∈(0,1)); H=0 if p=0 or 1.
      8. Weight:
             W = p * (1 - H)
         Laplace smoothing moves extreme p values towards center, slightly reducing weights for highly pure malware APIs (more conservative).
    Returns:
      df: DataFrame with APIs and statistics (sorted by weight descending)
      stats: summary statistics dict
    """
    from collections import defaultdict

    malware_count = defaultdict(int)
    benign_count = defaultdict(int)
    n_malware = 0
    n_benign = 0

    # Iterate over training samples and count
    for fpath, label in tqdm(train_items, desc="Read training cache and count APIs", disable=not verbose):
        sha = path_sha_no_ext(fpath)
        cache_file = cache_dir / f"{sha}.txt.gz"
        apis = read_api_cache(cache_file)
        apis_unique = set(apis)

        if label == "malware":
            n_malware += 1
            for api in apis_unique:
                malware_count[api] += 1
        elif label == "benign":
            n_benign += 1
            for api in apis_unique:
                benign_count[api] += 1

    all_apis = set(malware_count.keys()) | set(benign_count.keys())
    rows = []

    for api in all_apis:
        count_m = malware_count.get(api, 0)
        count_b = benign_count.get(api, 0)
        total_count = count_m + count_b
        if total_count < min_count:
            continue

        # Raw frequencies (not smoothed)
        pm_raw = count_m / n_malware if n_malware > 0 else 0.0
        pb_raw = count_b / n_benign if n_benign > 0 else 0.0

        # Laplace-smoothed frequencies (add α to counts only, denominator N + 2α)
        if n_malware > 0:
            pm = (count_m + alpha) / (n_malware + 2 * alpha)
        else:
            pm = 0.0
        if n_benign > 0:
            pb = (count_b + alpha) / (n_benign + 2 * alpha)
        else:
            pb = 0.0

        denom = pm + pb
        p = pm / denom if denom > 0 else 0.0

        H = 0.0
        if 0 < p < 1:
            H = -p * np.log(p) - (1 - p) * np.log(1 - p)

        H_norm = H / np.log(2.0)
        W = p * (1.0 - H_norm)

        rows.append({
            'API': api,
            'count_malware': int(count_m),
            'count_benign': int(count_b),
            'total_count': int(total_count),
            'pm_raw': float(pm_raw),
            'pb_raw': float(pb_raw),
            'pm': float(pm),
            'pb': float(pb),
            'p': float(p),
            'entropy': float(H),
            'weight': float(W),
        })

    df = pd.DataFrame(rows)
    if not df.empty:
        df = df.sort_values('weight', ascending=False)

    stats = {
        "n_malware_train": int(n_malware),
        "n_benign_train": int(n_benign),
        "n_api_after_filter": int(df.shape[0]),
        "min_count": int(min_count),
        "alpha": int(alpha),
        "smoothing_denominator_adjusted": False,  # Marked as not using standard form
    }
    return df, stats


def run_one_fold(fold_idx: int,
                 train_files: List[Path],
                 test_files: List[Path],
                 train_labels: List[str],
                 out_root: Path,
                 cache_dir: Path,
                 min_count: int,
                 verbose: bool):
    """
    One fold execution: write manifest -> calculate weights from cache -> write CSV/JSON outputs
    """
    fold_dir = out_root / f"fold_{fold_idx:02d}"
    fold_dir.mkdir(parents=True, exist_ok=True)

    # Save train/test sequence manifest
    (fold_dir / "train_seq_list.txt").write_text("\n".join(str(p) for p in train_files), encoding="utf-8")
    (fold_dir / "test_seq_list.txt").write_text("\n".join(str(p) for p in test_files), encoding="utf-8")

    # Save train/test sha lists (for filtering API sequences)
    train_shas = sorted({path_sha_no_ext(p) for p in train_files})
    test_shas = sorted({path_sha_no_ext(p) for p in test_files})
    (fold_dir / "train_sha.txt").write_text("\n".join(train_shas), encoding="utf-8")
    (fold_dir / "test_sha.txt").write_text("\n".join(test_shas), encoding="utf-8")

    # Calculate weights from training cache
    train_items = list(zip(train_files, train_labels))
    df_weights, stats = compute_weights_from_cache(
        train_items=train_items,
        cache_dir=cache_dir,
        min_count=min_count,
        verbose=verbose
    )
    weights_csv = fold_dir / "weights.csv"
    df_weights.to_csv(weights_csv, index=False, encoding="utf-8-sig")

    # Save meta info
    meta = {
        "fold": fold_idx,
        "n_train": int(len(train_files)),
        "n_test": int(len(test_files)),
        **stats
    }
    (fold_dir / "stats.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

    return {
        "fold": fold_idx,
        "weights_csv": str(weights_csv),
        "stats": meta
    }


# ========== Main process ==========
def main():
    # ---- Added: record start time ----
    start_ts = time.time()
    start_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(start_ts))
    # ----------------------------------

    parser = argparse.ArgumentParser(
        description='Sensitive API entropy and weight statistics (restore names from SAPI mapping based on .txt sequences produced by gexf_to_java_seq.py).')
    parser.add_argument('--root', type=str, default="/mnt/data2/wb2024/Methodology/MyWay/data/Sequences-md",
                        help='Root directory of sequence .txt files (output by gexf_to_java_seq.py)')
    parser.add_argument('--malware-key', type=str, default='malware', help='Malware directory keyword')
    parser.add_argument('--benign-key', type=str, default='benign', help='Benign directory keyword')
    parser.add_argument('--output-dir', type=str, default='/mnt/data2/wb2024/Methodology/MyWay2.0/fold_outputs-md', help='Output root for each fold')

    parser.add_argument('--sapi', type=str,
                        default="/mnt/data2/wb2024/Methodology/MyWay/analyze/删除没出现的结果API.txt",
                        help='Sensitive API list (must match the .txt sequence generation list, used to restore API name from ID)')

    parser.add_argument('--min-count', type=int, default=2, help='Minimum API occurrence to retain (based on training set statistics)')
    parser.add_argument('--n-splits', type=int, default=10, help='Number of cross-validation folds')
    parser.add_argument('--random-state', type=int, default=42, help='Random seed')
    parser.add_argument('--verbose', action='store_true', help='Show detailed progress', default=True)

    parser.add_argument('--workers', type=int, default=max(8, min(120, (os.cpu_count() or 64))),
                        help='Thread pool size for preprocessing (.txt read and ID parsing is IO-bound, thread pool is suitable)')
    parser.add_argument('--cache-dir', type=str, default=None, help='API cache directory (default: api_cache under output-dir)')
    parser.add_argument('--reuse-cache', action='store_true', default=True,
                        help='Reuse cache if it exists, skip .txt parsing')

    args = parser.parse_args()

    root = Path(args.root)
    out_root = Path(args.output_dir)
    out_root.mkdir(parents=True, exist_ok=True)
    cache_dir = Path(args.cache_dir) if args.cache_dir else (out_root / "api_cache")
    cache_dir.mkdir(parents=True, exist_ok=True)

    # 0) Load sensitive API mapping
    sapi_path = Path(args.sapi)
    if not sapi_path.exists():
        print(f"Sensitive API list not found: {sapi_path}")

        # Record finish time in log
        end_ts = time.time()
        end_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_ts))
        elapsed = end_ts - start_ts
        print(f"Elapsed: {elapsed:.2f}s")
        log_path = out_root / "run_time.log"
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(
                    f"Start: {start_str} | End: {end_str} | "
                    f"Elapsed: {elapsed:.2f}s | root: {root} | output-dir: {out_root} | note: sapi_not_found\n"
                )
        except Exception as e:
            print(f"WARNING: failed to write time log: {e}")
        return

    id_to_api, sapi_set = load_sapi_mapping(sapi_path)

    # 1) Enumerate sequence files and assign labels
    files_all = find_seq_txt_files(root)
    items = []
    for f in files_all:
        label = infer_label(f, args.malware_key, args.benign_key)
        if label in ('malware', 'benign'):
            items.append((Path(f), label))
    if not items:
        print("No sequence .txt files found with malware/benign label; check directory and keywords.")

        end_ts = time.time()
        end_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_ts))
        elapsed = end_ts - start_ts
        print(f"Elapsed: {elapsed:.2f}s")
        log_path = out_root / "run_time.log"
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(
                    f"Start: {start_str} | End: {end_str} | "
                    f"Elapsed: {elapsed:.2f}s | root: {root} | output-dir: {out_root} | note: no_labeled_items\n"
                )
        except Exception as e:
            print(f"WARNING: failed to write time log: {e}")
        return

    file_paths: List[Path] = [it[0] for it in items]
    labels: List[str] = [it[1] for it in items]
    y = np.array([1 if lab == 'malware' else 0 for lab in labels], dtype=int)

    # 2) Preprocessing: parallel parse all sequence files, extract sensitive APIs and cache (gzip)
    print(f"[INFO] Preprocessing sequence .txt files -> cache API list to: {cache_dir} , threads: {args.workers}, reuse_cache={args.reuse_cache}")
    tasks = []
    for f in file_paths:
        tasks.append((
            str(f),
            args.malware_key,
            args.benign_key,
            str(cache_dir),
            bool(args.reuse_cache),
            id_to_api,
            sapi_set,
        ))

    index_rows = []
    n_errors = 0
    # Use thread pool: IO heavy, avoid repeated SAPI mapping loads
    with cf.ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = [ex.submit(preprocess_one_file, t) for t in tasks]
        for fut in tqdm(cf.as_completed(futures), total=len(futures), desc="Preprocessing sequence .txt", disable=not args.verbose):
            info = fut.result()
            index_rows.append(info)
            if info.get("error"):
                n_errors += 1
                print(f"[ERROR] Preprocessing failed: {info['path']}\n{info['error']}")

    # Save index (for debugging and reuse)
    index_df = pd.DataFrame(index_rows)
    index_csv = out_root / "api_cache_index.csv"
    index_df.to_csv(index_csv, index=False, encoding="utf-8-sig")
    print(f"[INFO] Saved cache index: {index_csv}, failures: {n_errors}")

    # 3) Stratified cross split
    skf = StratifiedKFold(n_splits=args.n_splits, shuffle=True, random_state=args.random_state)
    print(f"Total {len(file_paths)} sequence files, running {args.n_splits}-fold stratified CV...")

    # 4) Sequentially run each fold (removed --fold-workers)
    results = []
    for fold_idx, (train_idx, test_idx) in enumerate(skf.split(np.zeros(len(file_paths)), y), start=1):
        train_files = [file_paths[i] for i in train_idx]
        test_files = [file_paths[i] for i in test_idx]
        train_labels = [labels[i] for i in train_idx]

        r = run_one_fold(
            fold_idx=fold_idx,
            train_files=train_files,
            test_files=test_files,
            train_labels=train_labels,
            out_root=out_root,
            cache_dir=cache_dir,
            min_count=args.min_count,
            verbose=args.verbose
        )
        results.append(r)

    # Print summary
    for r in sorted(results, key=lambda x: x["fold"]):
        print(f"[Fold {r['fold']:02d}] Saved weights: {r['weights_csv']}  Stats: n_train={r['stats']['n_train']} n_test={r['stats']['n_test']} n_api_after_filter={r['stats']['n_api_after_filter']}")

    # ---- Added: end time & log ----
    end_ts = time.time()
    end_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(end_ts))
    elapsed = end_ts - start_ts
    print(f"Elapsed: {elapsed:.2f}s")

    log_path = out_root / "run_time.log"
    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(
                f"Start: {start_str} | End: {end_str} | "
                f"Elapsed: {elapsed:.2f}s | root: {root} | output-dir: {out_root} | "
                f"n_splits={args.n_splits} | workers={args.workers} | reuse_cache={args.reuse_cache}\n"
            )
    except Exception as e:
        print(f"WARNING: failed to write time log: {e}")
    # --------------------------------


if __name__ == '__main__':
    main()